#! /bin/sh
set -e

###########################################
# Initializes the k8s cluster on the local machine
#
#   STDOUT: Output of kubeadm join
#   STDERR: Output of kubeadm join

kubeadm init \
    --control-plane-endpoint '{{k8s_apiserver_hostname}}.{{k8s_cluster_dnsname}}:{{k8s_apiserver_port}}' \
    --service-dns-domain '{{k8s_cluster_dnsname}}' \
    --pod-network-cidr '{{k8s_pod_network_cidr}}' \
    --service-cidr '{{k8s_service_cidr}}' \
    --apiserver-advertise-address '{{ ansible_facts[host_primary_interface_name].ipv4.address }}' \
    --kubernetes-version '{{k8s_version}}' \
    --apiserver-bind-port 6443 \
    --upload-certs

mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config
echo 'source <(kubectl completion bash)' >>~/.bashrc