###########################################
## This checks the cluster state
##
## It sets the k8s_config_server environment-variable, to the url of
## the apiserver. If the host is not member of a cluster, it is blank


###########################################
## scripts ~/initk8s

- name: "sync ~/initk8s script to setup cluster"
  template:
    src: initk8s
    dest: ~/initk8s

- file:
    path: ~/initk8s
    mode: '755'


###########################################
## Execute the init-script

- name: "Initialize kubernetes cluster, you may cat ~/kubeadm.log in ssh to check progress"
  shell: ~/initk8s >> ~/kubeadm.log
  when: setup_manual_kubeadm == false
