#!/bin/bash

set -e

for i in "$@"
do
case $i in

    -h|--help)
    echo "Usage:"
    echo "$0 <path_to_config.yml>"
    echo "Example: $0 conf/k8sdev.yml"
    exit 0
    ;;

    # -short=*|--long=*)
    # VARIABLE="${i#*=}"
    # shift # past --configfile=value | 
    # ;;

    *)
    CONFIGFILE=$i
    shift # past argument with no value
    ;;

esac
done

if [ -z "$CONFIGFILE" ]; then
    echo "Invalid args. Use --help."
    exit 1
fi

if [ ! -e "$CONFIGFILE" ]; then
    echo "Configfile $CONFIGFILE not found."
    exit 1
fi

ansible-playbook lib/ansible/hostplaybook.yml -e @"$CONFIGFILE"
