#! /bin/sh
set -x

###########################################
# Joins the local machine as a worker
#
#   STDOUT: Output of kubeadm join
#   STDERR: Output of kubeadm join

cd ~
{{ join_cmd.stdout }}
