# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports

- name: "firewall: allow 10250/tcp for kube-apiserver"
  firewalld:
    port: "{{ k8s_apiserver_port }}/tcp"   #Kubernetes API server
    permanent: yes
    state: enabled
  notify: reload firewalld

- name: "firewall: 2379-2380/tcp for etcd server"
  firewalld:
    port: 2379-2380/tcp   # etcd server client API
    permanent: yes
    state: enabled
  notify: reload firewalld

# 10250/tcp for Kublet API is in lnxcommon role

- name: "firewall: 10251/tcp for kube-scheduler"
  firewalld:
    port: 10251/tcp   # kube-scheduler
    permanent: yes
    state: enabled
  notify: reload firewalld

- name: "firewall: 10252/tcp for kube-controller-manager"
  firewalld:
    port: 10252/tcp   # kube-controller-manager
    permanent: yes
    state: enabled
  notify: reload firewalld

- debug:
    msg: "kubeadm init --control-plane-endpoint '{{k8s_apiserver_hostname}}.{{k8s_cluster_dnsname}}:{{k8s_apiserver_port}}' --service-dns-domain '{{k8s_cluster_dnsname}}' --pod-network-cidr '{{k8s_pod_network_cidr}}' --upload-certs"

# kubectl
#  mkdir -p $HOME/.kube
#  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#  sudo chown $(id -u):$(id -g) $HOME/.kube/config

