#! /bin/sh
set -e

###########################################
# Joins the local machine as a control plane
#
#   STDOUT: Output of kubeadm join
#   STDERR: Output of kubeadm join

cd ~
{{ join_cmd.stdout }} \
    --control-plane \
    --certificate-key {{ cert_cmd.stdout }} \
    --apiserver-advertise-address {{ ansible_facts['eth1'].ipv4.address }} \
    --apiserver-bind-port 6443
