- name: ensure ntpd is at the latest version
  yum: pkg=ntp state=latest
  notify:
  - restart ntpd

- name: Enable and start firewall service
  service:
    name: firewalld
    enabled: yes
    state: started

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
- name: "firewall: allow 10250/tcp for Kublet API"
  firewalld:
    port: 10250/tcp
    permanent: yes
    state: enabled
  notify: reload firewalld

# http://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/
- name: Disable swap if enabled (swaptotal={{ansible_facts['swaptotal_mb']}})
  when: ansible_facts['swaptotal_mb'] != 0
  shell: |
    swapoff -a
  notify:
    - disable swap permanently

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
- name: Add kubernetes yum repo
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install kubelet kubeadm kubectl
  yum:
    disable_excludes: kubernetes
    name:
      - kubelet
      - kubeadm
      - kubectl
