- name: ensure ntpd is at the latest version
  yum: pkg=ntp state=latest
  notify:
  - restart ntpd

- name: Enable and start firewall service
  service:
    name: firewalld
    enabled: yes
    state: started

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
- name: "firewall: allow 10250/tcp for kube-apiserver"
  firewalld:
    port: 10250/tcp   #Kubernetes API server
    permanent: yes
    state: enabled

# http://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/
- name: Disable swap if enabled (swaptotal={{ansible_facts['swaptotal_mb']}})
  when: ansible_facts['swaptotal_mb'] != 0
  shell: |
    swapoff -a
  notify:
    - disable swap permanently
