#! /bin/sh
set -e

###########################################
# Determinates the k8s configuration state of the machine
#
#   STDOUT: (don't change, as is will be read in the task!)
#   "k8s_configured=no" => kubeadm init / join have not been performed
#   "k8s_configured=yes" => kubeadm init / join have been performed
#
#   STDERR: any other status or error message
# exit when any command fails

CONFFILE=/etc/kubernetes/kubelet.conf

if [ ! -f "$CONFFILE" ]; then
    echo "k8s_configured=no"
    exit 0
fi

EXPECTED_URL='https://{{k8s_apiserver_hostname}}.{{k8s_cluster_dnsname}}:{{k8s_apiserver_port}}'
CONFIGURED_URL=$(cat $CONFFILE | grep "server: " | awk '{print $2}')

echo "Configured URL: $CONFIGURED_URL"
echo "Expected URL: $EXPECTED_URL"

if [ "$EXPECTED_URL" == "$CONFIGURED_URL" ]; then
    echo "k8s_configured=yes"
    exit 0
else
    >&2 echo "This node is not member of the configured cluster! You may create a new node from scratch. "
fi