# https://docs.ansible.com/ansible/latest/modules/list_of_windows_modules.html
# if you want de-AT keyboard in powerhsell execute:
# Set-WinUserLanguageList -LanguageList de-AT -Force


# todo: ntpd
# todo: check about to disable pagefile (=SWAP) for windows workers


# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
- name: "windows firewall: allow 10250/tcp for kube-apiserver"
  win_firewall_rule:
    action: allow
    name: "kubeapiserver"
    localport: 10250
    protocol: tcp
    direction: in    

- name: Ensure 'Containers' Windows Feature
  # https://docs.ansible.com/ansible/2.5/modules/win_feature_module.html
  win_feature:
    name: containers
    state: present
    include_sub_features: yes
  register: reboot_required

# https://docs.docker.com/install/windows/docker-ee/#use-a-script-to-install-docker-ee

- name: create the install-docker.ps1 script
  win_template:
    src: install-docker.ps1
    dest: c:\install-docker.ps1


- name: Ensure docker installed (will take some time for download)
  win_command: powershell.exe -File install-docker.ps1
  args:
    chdir: c:\
    creates: c:\docker

- name: Enable and start docker service
  win_service:
    name: docker
    start_mode: auto
    state: started

- name: Perform Reboot, if required
  win_reboot:
  when: reboot_required.changed
