###########################################
## This is the role joins new clp nodes to the cluster
##
## It is dynamically included by hostplaybook.yml

- name: Get Join-Token from lnxclp-setup
  command: kubeadm token create --print-join-command
  delegate_to: "{{ groups['lnxclp-setup'] | first }}"
  run_once: true
  register: join_cmd

- name: Get Certificate-Key from lnxclp-setup
  shell: kubeadm init phase upload-certs --upload-certs | tail -n 1
  delegate_to: "{{ groups['lnxclp-setup'] | first }}"
  run_once: true
  register: cert_cmd

- name: "sync ~/joink8s script to setup cluster"
  template:
    src: joink8s
    dest: ~/joink8s
    mode: 755

- name: "Join kubernetes cluster, you may cat ~/kubeadm.log in ssh to check progress"
  shell: ~/joink8s >> ~/kubeadm.log
  when: setup_manual_kubeadm == false
