#! /bin/sh
set -e

###########################################
# Initializes the k8s cluster on the local machine
#
#   STDOUT: Output of kubeadm join
#   STDERR: Output of kubeadm join

kubeadm init \
    --control-plane-endpoint '{{k8s_cluster_url}}' \
    --service-dns-domain '{{k8s_cluster_dnsname}}' \
    --pod-network-cidr '{{k8s_pod_network_cidr}}' \
    --apiserver-advertise-address {{ ansible_facts['eth1'].ipv4.address }} \
    --apiserver-bind-port 6443 \
    --upload-certs

mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config
echo 'source <(kubectl completion bash)' >>~/.bashrc