---
# We fail if ansible is not 2.0, just because we the the compatiblity-mode
# to '2.0' in the Vagrantfile. It may also work with new versions, if they are available.
- hosts: all
  tasks:
    - debug:
        msg: "Ansible version is {{ ansible_version.full }}"
    - fail:
      name: Fail if ansible != 2.*.*
      when: ansible_version.major != 2

    - set_fact:
        k8s_cluster_url: '{{k8s_apiserver_hostname}}.{{k8s_cluster_dnsname}}:{{k8s_apiserver_port}}'
        k8s_cluster_url_with_protocol: 'https://{{k8s_apiserver_hostname}}.{{k8s_cluster_dnsname}}:{{k8s_apiserver_port}}'
