- name: Set current version
  set_fact:
    current_version: v1.2.4

- name: ~/k8smanifests directory exists
  file:
    path: ~/k8smanifests
    state: directory

- name: Sync haproxy-ingress.{{current_version}}.yml
  template:
    src: haproxy-ingress.{{current_version}}.yml
    dest: ~/k8smanifests/haproxy-ingress.{{current_version}}.yml

- name: Apply haproxy-ingress.yml
  command: kubectl apply -f ~/k8smanifests/haproxy-ingress.{{current_version}}.yml

