# recommended version
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
# see versions: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/
# https://docs.docker.com/engine/release-notes/
lnx_docker_version: "18.06.3"
win_docker_version: "19.03.3"

## Setup options
#############################################################

# to reduce the time of provisioning, you may skip the system_setup phase,
# if this has already been done. This is just an optimization for development. 
setup_skip_system_setup: no

# if this is enabled, all yum packages are updated on start
setup_update_all_packages: no

# the playbook will only init a new cluster, if this enabled
# this is for safty, to make sure that an existing cluster is untouched
setup_create_new_k8s_cluster: yes

# the playbook will create k8sinit, k8sjoin and k8steardown scripts, but don't execute them
# this is specially for testing, to see timeing and stdout / stderr
setup_manual_kubeadm: false

## Kubernetes global cluster configuration
#############################################################

# 6443 is the default port:
k8s_apiserver_port: 6443

# the CIDR used for the pod network, need to be used for routing
k8s_pod_network_cidr: 10.244.0.0/16

# we use the ip of clp1, because there is no keealived yet **)
k8s_api_server_vip: 10.0.0.2

# the base dnsname for the cluster  **)
k8s_cluster_dnsname: k8stest.local

# the hostname used for the apiserver (without the k8s_cluster_dnsname) **)
k8s_apiserver_hostname: apiserver

# to install the flannel CNI plugin
# we will evalute the 'Host Gateway Mode' as an alternative, specially how it 
# plays well with kubadm
k8s_install_flannel: yes

## Notes
#############################################################
#
# **): If you use Vagrant for local machine tests, these values will be
#       set from the .env file in the project root. Change them in this file
#
# Parameters, only passed by Vagrant:
#   k8s_enable_proxy: yes


test_var:
  - 10
  - 11
  - 12