#! /bin/sh
apiserverendpoint='{{k8s_apiserver_hostname}}.{{k8s_cluster_dnsname}}:{{k8s_apiserver_port}}'

kubeadm init \
    --control-plane-endpoint $apiserverendpoint \
    --service-dns-domain '{{k8s_cluster_dnsname}}' \
    --pod-network-cidr '{{k8s_pod_network_cidr}}' \
    --upload-certs

mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config
