###########################################
## This role joins nodes to an existing cluster
## It is added dynamically by lnxclp and lnxwrk, if new nodes need to join

- name: Get Join-Token from lnxclp-setup
  command: kubeadm token create --print-join-command
  delegate_to: "{{ groups['lnxclp-setup'] | first }}"
  run_once: true
  register: join_cmd

- name: "sync ~/joink8s script to setup cluster"
  template:
    src: joink8s
    dest: ~/joink8s
    mode: 755

- name: "Join kubernetes cluster, you may cat ~/kubeadm.log in ssh to check progress"
  shell: ~/joink8s >> ~/kubeadm.log
  when: setup_manual_kubeadm == false
