#! /bin/sh
set -e

###########################################
# Deletes the local cluster state
#   
#   THIS IS FOR TESTING ONLY!
#   NOT TESTED FOR PRODUCTION USE!

kubeadm reset -f

# remove config
rm -rf /etc/kubernetes/*
rm -rf ~/.kube

# and recreate manifests, as these existed before kubeadm init
mkdir -p /etc/kubernetes/manifests
